apps/noticia/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

from apps.noticia.views import *
from django.utils.translation import ugettext_lazy as _

urlpatterns = patterns('apps.noticia.views',
    url(r'^$', PostListView.as_view(), name="posts"),
    url(_(r'^tag/(?P<slug>.+?)/$'), TagPostView.as_view(), name="tag"),
    url(_(r'^categoria/(?P<slug>.+?)/$'), CategoriaPostView.as_view(), name="categoria"),
    url(_(r'^arquivo/(?P<ano>\d+)/$'), ArquivoPostView.as_view(), name="arquivo"),
    url(_(r'^download/(?P<pdf>.+?)$'), DownloadView.as_view(), name="download"),
    url(_(r'^(?P<slug>.+?)/$'), PostView.as_view(), name="post"),
)

apps/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, include, url
from django.templatetags.i18n import language
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib import admin
from apps.apresentacao.views import *
from apps.contato.views import *
from apps.cotacao.views import *

from django.conf.urls.i18n import i18n_patterns
from django.core.urlresolvers import reverse
from django.utils.translation import activate

from django.utils.translation import ugettext_lazy as _


# urlpatterns = patterns('',
#     # Examples:
#     url(r'^$', TemplateView.as_view(template_name="select-language.html"), name="language"),
# )

urlpatterns = [
    # url(r'^$', LanguageView.as_view()),
    url(r'^$', TemplateView.as_view(template_name="select-language.html"), name="language"),
    url(r'^set_language/(?P<language>[\w-]+)$', LanguageView.as_view(), name="set_language"),
]

urlpatterns += i18n_patterns(
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(_(r'^home/$'), HomeView.as_view(), name="home"),
    url(_(r'^apresentacao/'), include('apps.apresentacao.urls', namespace="apresentacao")),
    url(_(r'^nossos-servicos/'), include('apps.servico.urls', namespace="servico")),
    url(_(r'^produtos/'), include('apps.produto.urls', namespace="produto")),
    url(_(r'^noticias/'), include('apps.noticia.urls', namespace="noticia")),
    url(_(r'^obter-cotacao/'), CotacaoView.as_view(), name="cotacao"),
    url(_(r'^contato/'), ContatoView.as_view(), name="contato"),

    # #url de terceiros
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

apps/noticia/models.py
# -*- coding:utf-8 -*-
from apps import settings
from django.db import models
import datetime
import os
from uuid import uuid4
from django.utils.deconstruct import deconstructible
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField
from django.template.defaultfilters import slugify

BOLEAN_CHOISES = (   
      (0,'Não'),
      (1,'Sim'),      
    )

STATUS_CHOISES = (   
      (0,'Rascunho'),
      (1,'Publicar'),      
    )

@deconstructible
class PathAndRename(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')        
        # set filename as random string
        filename = '%s.%s'%(slugify(ext[0]), ext[-1])
        # return the whole path to the file
        return os.path.join(self.path, filename)

path = "uploads/{:%Y/%m}/".format(datetime.datetime.now())        
path_and_rename = PathAndRename(path)


class CategoriaPost(models.Model): 

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'    

    nome = models.CharField(u'Nome', max_length=150)
    slug = models.SlugField(u'URL', max_length=150,blank=True,null=True,unique=True)    
    ativo = models.BooleanField(u'Ativo',default=1)
    categoria_pai = models.ForeignKey(u'self', null=True,blank=True, related_name='self__categoria')
    imagem = models.ImageField(u'Imagem', upload_to=path_and_rename, max_length=255,null=True,blank=True,default=None)
    idioma = models.CharField(u'Idioma', choices=settings.LANGUAGES, max_length=15, null=True, blank=True)
    date_joined = models.DateTimeField('Criado em',auto_now_add=True)
    date_update = models.DateTimeField('Atualizado em',auto_now=True)

    def __unicode__(self):
        return self.nome


class Tag(models.Model): 

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'
    
    nome = models.CharField(u'Tag', max_length=150)    
    slug = models.SlugField(u'URL', max_length=150,blank=True,null=True,unique=True)
    ativo = models.BooleanField(u'Ativo',default=1)
    idioma = models.CharField(u'Idioma', choices=settings.LANGUAGES, max_length=15, null=True, blank=True)
    date_joined = models.DateTimeField('Criado em',auto_now_add=True)
    date_update = models.DateTimeField('Atualizado em',auto_now=True)

    def __unicode__(self):
        return self.nome        

class Post(models.Model): 

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        ordering = ['-data_publicacao']
    
    data_publicacao = models.DateTimeField('Data de Publicação',null=False,blank=False)
    titulo = models.CharField(u'Titulo', max_length=150)    
    texto = RichTextField(u'Texto',blank=True,null=True)
    slug = models.SlugField(u'URL', max_length=150,blank=True,null=True,unique=True)
    imagem = models.ImageField(u'Imagem',help_text="720x300", upload_to=path_and_rename, max_length=255,null=True,blank=True,default=None)
    fixar = models.BooleanField(u'Fixar na Home',default=False) 
    ativo = models.BooleanField(u'Ativo',default=1)
    ordem = models.PositiveSmallIntegerField(u'Ordem',default=1)
    categorias = models.ManyToManyField(CategoriaPost, null=True, blank=True)
    tags = models.ManyToManyField(Tag, null=True, blank=True)
    autor = models.ForeignKey(User,verbose_name="Autor", default=None, related_name='autor_post', blank=True, null=True)
    date_joined = models.DateTimeField('Criado em',auto_now_add=True)
    ultima_modificacao = models.ForeignKey(User,verbose_name="modificado por", default=None, related_name='modificacao_post', blank=True, null=True)
    date_update = models.DateTimeField('Modificado em',auto_now=True)
    idioma = models.CharField(u'Idioma', choices=settings.LANGUAGES, max_length=15, null=True, blank=True)
       
    
    def __unicode__(self):
        return self.titulo

class Arquivo(models.Model): 

    class Meta:
        verbose_name = 'Arquivo'
        verbose_name_plural = 'Arquivos'
    
    post = models.ForeignKey(Post,verbose_name="Post", default=None, blank=True, null=True)   
    titulo = models.CharField(u'Titulo do Arquivo', max_length=150,null=True,blank=True)    
    arquivo = models.FileField(u'Arquivo', upload_to=path_and_rename, max_length=255,null=True,blank=True,default=None)
    ativo = models.BooleanField(u'Ativo',default=1)
    date_joined = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)
    idioma = models.CharField(u'Idioma', choices=settings.LANGUAGES, max_length=15, null=True, blank=True)

    def __unicode__(self):
        return self.titulo

apps/noticia/forms.py
# -*- coding:utf-8 -*-
from django.forms import ModelForm
from django.contrib.auth.models import User
from apps.noticia.models import Post

class PostForm(ModelForm):
    # class Meta:
    #     model = Post

    def clean_autor(self):
        if not self.cleaned_data['autor']:
            return User()
        return self.cleaned_data['autor']

    def clean_ultima_modificacao(self):
        if not self.cleaned_data['ultima_modificacao']:
            return User()
        return self.cleaned_data['ultima_modificacao']

apps/noticia/views.py
# -*- coding:utf-8 -*-
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render_to_response, HttpResponse

from apps.noticia.models import *

from django.conf import settings
from django.db.models import Q
import datetime
from django.utils.translation import get_language
from django.views.generic import View, TemplateView, ListView, DetailView
from django.utils.html import strip_tags


class PostListView(ListView):

    template_name = 'noticia/index.html'
    paginate_by = 4
    context_object_name = 'items'
    queryset = None
    now = datetime.datetime.now()

    def get_queryset(self):

        idioma = get_language()
        items = Post.objects.filter(Q(ativo=True) & Q(data_publicacao__lte=self.now) & Q(idioma=idioma)).order_by('-data_publicacao')

        for i in items:
            if not i.imagem:
                for x in i.categorias.all():
                    if x.imagem:
                        i.imagem_categoria = x.imagem
                        break

        queryset = items
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super(PostListView, self).get_context_data(*args, **kwargs)
        idioma = get_language()
        context['last_item'] = Post.objects.filter(Q(ativo=True) & Q(data_publicacao__lte=self.now) & Q(idioma=idioma)).order_by('-data_publicacao').last()
        return context

    def get_template_names(self):

        template_name = self.template_name

        if self.request.is_ajax():
            template_name = 'noticia/index_ajax.html'

        return [template_name]

class TagPostView(PostListView):

    def get(self,request,*args,**kwargs):

        items = Post.objects.filter(Q(ativo=True) & Q(data_publicacao__lte=self.now) & Q(tags__slug=kwargs.get('slug'))).order_by('-data_publicacao')

        for i in items:
            if not i.imagem:
                for x in i.categorias.all():
                    if x.imagem:
                        i.imagem_categoria = x.imagem
                        break

        self.queryset = items

        return super(TagPostView, self).get(request, *args, **kwargs)

class CategoriaPostView(PostListView):

    def get(self,request,*args,**kwargs):

        items = Post.objects.filter(Q(ativo=True) & Q(data_publicacao__lte=self.now) & Q(categorias__slug=kwargs.get('slug'))).order_by('-data_publicacao')

        for i in items:
            if not i.imagem:
                for x in i.categorias.all():
                    if x.imagem:
                        i.imagem_categoria = x.imagem
                        break

        self.queryset = items

        return super(CategoriaPostView, self).get(request, *args, **kwargs)


class ArquivoPostView(PostListView):

    def get(self,request,*args,**kwargs):

        items = Post.objects.filter(Q(ativo=True) & Q(data_publicacao__year=kwargs.get('ano')) & Q(data_publicacao__lte=self.now)).order_by('-data_publicacao')[:4]

        for i in items:
            if not i.imagem:
                for x in i.categorias.all():
                    if x.imagem:
                        i.imagem_categoria = x.imagem
                        break

        self.queryset = items

        return super(ArquivoPostView, self).get(request, *args, **kwargs)

class PostView(DetailView):

    template_name = 'noticia/post.html'

    model = Post

    context_object_name = 'item'

    def get_object(self,queryset=None):

        """
        Returns the object the view is displaying.
        By default this requires `self.queryset` and a `pk` or `slug` argument
        in the URLconf, but subclasses can override this to return any object.
        """
        # Use a custom queryset if provided; this is required for subclasses
        # like DateDetailView
        if queryset is None:
            queryset = self.get_queryset()
        # Next, try looking up by primary key.
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        slug = self.kwargs.get(self.slug_url_kwarg, None)
        if pk is not None:
            queryset = queryset.filter(pk=pk)
        # Next, try looking up by slug.
        elif slug is not None:
            slug_field = self.get_slug_field()
            queryset = queryset.filter(**{slug_field: slug})
        # If none of those are defined, it's an error.
        else:
            raise AttributeError("Generic detail view %s must be called with "
                                 "either an object pk or a slug."
                                 % self.__class__.__name__)
        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
            if not obj.imagem:
                for x in obj.categorias.all():

                    if x.imagem:
                        obj.imagem_categoria = x.imagem
                        break

        except queryset.model.DoesNotExist:
            raise Http404(_("No %(verbose_name)s found matching the query") %
                          {'verbose_name': queryset.model._meta.verbose_name})
        return obj




class DownloadView(View):

    def get(self, request, *args, **kwargs):

        import mimetypes
        from os import path

        arquivo = "%s/%s" % (settings.MEDIA_ROOT, kwargs.get('pdf'))

        if not (path.exists(arquivo)):
            raise Http404()

        mimetype, encoding = mimetypes.guess_type(arquivo)

        if mimetype is None:
            mimetype = 'application/force-download'

        file = arquivo.split("/")[-1]

        response = HttpResponse(open(arquivo, 'r').read())
        response['Content-Type'] = mimetype
        response['Pragma'] = 'public'
        response['Expires'] = '0'
        response['Cache-Control'] = 'must-revalidate, post-check=0, pre-check=0'
        response['Content-Disposition'] = 'attachment; filename=%s' % file
        response['Content-Transfer-Encoding'] = 'binary'
        response['Content-Length'] = str(path.getsize(arquivo))
        return response

apps/noticia/templates/noticia/base.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load i18n %}
{% load thumbnail %}
{% load noticia_extras %}

{% block  title %}
    {% trans 'Notícias' %}
{% endblock title %}

{% block content %}
    <section class="home-header interna">
        <div class="bg-title bg-noticias"></div>
        <div class="header-title interna text-center-xs">
          <h1 class="container"><span class="text-light">{% trans 'CENTRAL DE' %}</span><br>{% trans 'NOTÍCIAS' %}</h1>
        </div>
    </section>
{% endblock content %}

{% block container %}
    <main class="section-padding">
        <div class="container">
            <div class="row">
                <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{% trans 'ÚLTIMAS NOTÍCIAS' %}</h2>
            </div>

            <!-- NOTICIAS -->
            {% if last_item %}
                <!--DESTAQUE-->
                <div class="row">
                    <div class="col-xs-12 news-destaque">
                        {% if last_item.imagem or last_item.imagem_categoria %}
                            {% if last_item.imagem %}
                                {% thumbnail last_item.imagem "640x320" crop="center"  as im %}
                                    <img class="news-image" src="{{ im.url }}" alt="{{last_item.titulo}}">
                                {% endthumbnail %}
                            {%else%}
                                {% thumbnail last_item.imagem_categoria "640x320" crop="center"  as im %}
                                    <img class="news-image" src="{{ im.url }}" alt="{{last_item.titulo}}">
                                {% endthumbnail %}
                            {%endif%}
                        {%endif%}
                        <p class="news-link-title">
                            <a href="{% url 'noticia:post' last_item.slug %}">{{last_item.titulo}}</a>
                        </p>
                        <time class="news-time" datetime="2014-01-01">{{last_item.data_publicacao}}</time>
                        <p>{{ last_item.texto|safe|striptags|truncatechars:320 }}</p>
                        <a href="{% url 'noticia:post' last_item.slug %}" class="btn btn-small btn-rounded btn-block-mobile">{% trans 'Leia Mais' %}</a>
                    </div>
                </div>
            {% endif %}

            <!-- NOTICIAS -->
            {% block main %}

            {% endblock main %}
        </div>
    </main>
{% endblock container %}
<!-- Fim -->

{% block js %}
    <script type="text/javascript" src="{% static 'js/paginator.js' %}"></script>
{% endblock js %}

apps/noticia/templates/noticia/index.html
{% extends 'noticia/base.html' %}
{% load staticfiles %}

{% load i18n %}
{% load thumbnail %}
{% load noticia_extras %}

{% block main %}
<div class="list-all-news">
    <div class="row animate-context">
        <section>
            <div class="list-news">
                {% for item in items %}
                    <div class="col-xs-10 col-xs-push-1 col-sm-push-0 col-sm-6 col-md-3 news hidding">
                        <!--Post's Start -->
                            <div class="news-wrapper">
                                <!--IMAGEM-->
                                <a class="news-link-img" href="{% url 'noticia:post' item.slug %}">
                                    {% if item.imagem or item.imagem_categoria %}
                                        {% if item.imagem %}
                                            {% thumbnail item.imagem "345x241" crop="center" as im %}
                                                <img class="img-responsive" src="{{ im.url }}" alt="{{item.titulo}}">
                                            {% endthumbnail %}
                                        {%else%}
                                            {% thumbnail item.imagem_categoria "345x241" crop="center"  as im %}
                                                <img class="img-responsive" src="{{ im.url }}" alt="{{item.titulo}}">
                                            {% endthumbnail %}
                                        {%endif%}
                                    {%endif%}
                                </a>
                                <!--TITULO-->
                                <p class="news-link-title">
                                    <a href="{% url 'noticia:post' item.slug %}">{{ item.titulo }}</a>
                                </p>
                                <!--DATA NOTICIA-->
                                <time datetime="{{ item.data_publicacao|date:'Y-m-d' }}">{{ item.data_publicacao }}</time>
                                <!--PREV.TEXTO-->
                                <p class="news-desc">{{ item.texto|safe|striptags|truncatechars:261 }}</p>
                            </div>
                        <!--Post's End -->
                        </div>
                {% endfor %}
                </div>
                </section>
                </div>

</div>
    {% if is_paginated %}
        <div class="action-button hidding animate container">
            <div class="col-xs-12">
                    <a href="?page={{ page_obj.first_page }}" rel="{% url 'noticia:posts' %}" data-page='1' data-numpages="{{ page_obj.paginator.num_pages }}" title="{% trans 'Ver mais' %}" class="vermais btn btn-small btn-rounded btn-block-mobile" data-texto="{% trans 'Ver mais' %}">
                        <span class="anime2">{% trans 'Ver mais' %}</span>
                    </a>
            </div>
        </div>
    {% endif %}


{% endblock main %}

{% block extrajs %}
    <script src="{% static 'js/paginator.js' %}"></script>
{% endblock extrajs %}

apps/noticia/templates/noticia/index_ajax.html
{% load staticfiles %}

{% load noticia_extras %}
{% load i18n %}
{% load i18n %}
{% load thumbnail %}
<div class="row animate-context">
    <section>
        <div class="list-news">
             {% for item in items %}
                <div class="col-xs-10 col-xs-push-1 col-sm-push-0 col-sm-6 col-md-3 news hidding">
                    <!--Post's Start -->
                        <div class="news-wrapper">
                            <!--IMAGEM-->
                            <a class="news-link-img" href="{% url 'noticia:post' item.slug %}">
                                {% if item.imagem or item.imagem_categoria %}
                                    {% if item.imagem %}
                                        {% thumbnail item.imagem "345x241" crop="center" as im %}
                                            <img class="img-responsive" src="{{ im.url }}" alt="{{item.titulo}}">
                                        {% endthumbnail %}
                                    {%else%}
                                        {% thumbnail item.imagem_categoria "345x241" crop="center"  as im %}
                                            <img class="img-responsive" src="{{ im.url }}" alt="{{item.titulo}}">
                                        {% endthumbnail %}
                                    {%endif%}
                                {%endif%}
                            </a>
                            <!--TITULO-->
                            <p class="news-link-title">
                                <a href="{% url 'noticia:post' item.slug %}">{{ item.titulo }}</a>
                            </p>
                            <!--DATA NOTICIA-->
                            <time datetime="2014-01-01">{{ item.data_publicacao }}</time>
                            <!--PREV.TEXTO-->
                            <p class="news-desc">{{ item.texto|safe|striptags|truncatechars:261 }}</p>
                        </div>
                    <!--Post's End -->
                    </div>
            {% endfor %}
        </div>
    </section>
</div>

apps/noticia/templates/noticia/post.html
{% extends 'noticia/base.html' %}
{% load staticfiles %}

{% load i18n %}
{% load thumbnail %}
{% load noticia_extras %}

{% block matatags_extras %}
	<meta property="og:locale" content="pt_BR">

	<meta property="og:url" content="http://{{request.META.HTTP_HOST}}{% url 'noticia:post' item.slug %}">

	<meta property="og:title" content="{{item.titulo}}">
	<meta property="og:site_name" content="Equalize LTD">

	<meta property="og:description" content="{{ item.texto|safe|striptags }}">

	{% if item.imagem %}
	    {% thumbnail item.imagem "640x150" as im %}
	       <meta property="og:image" content="{{request.META.HTTP_HOST}}{{ im.url }}">
	    {% endthumbnail %}
	{%else%}
		{% thumbnail item.imagem_categoria "640x150" as im %}
	     <meta property="og:image" content="{{request.META.HTTP_HOST}}{{ im.url }}">
	    {% endthumbnail %}
	{%endif%}

	<meta property="og:image:type" content="image/jpeg">
	<meta property="og:image:width" content="770">
	<meta property="og:image:height" content="400">
	<meta property="og:type" content="website">

{% endblock matatags_extras %}

{% block title %} {{ item.titulo }} {%endblock%}

{% block container %}
    <main class="section-padding">
        <div class="container">
            <div class="row">
                <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{{item.titulo}}</h2>
            </div>

            <div class="row"></div>

            <div class="row">
                <div class="col-xs-12 news-destaque">
                    <time class="news-time" datetime="2014-01-01">{{item.data_publicacao}}</time>
                    <div class="news-desc">
                        <p>{{ item.texto|safe|escape }}</p>
                    </div>
                </div>
            </div>

            <div class="action-button hiddin animate container">
                <div class="col-xs-12">
                    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-small btn-rounded btn-block-mobile">{% trans 'VOLTAR' %}</a>
                </div>
            </div>
        </div>
    </main>
{% endblock container %}