apps/produto/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from apps.produto.views import *

from django.utils.translation import ugettext_lazy as _

urlpatterns = patterns('apps.produto.views',

    url(_(r'^textil/$'), TextilListView.as_view(), name="textil"),
    url(_(r'^eletronicos/$'), EletronicoListView.as_view(), name="eletronico"),
    url(_(r'^construcao/$'), ConstrucaoListView.as_view(), name="construcao"),
    url(_(r'^promocionais/$'), PromocionalListView.as_view(), name="promocional"),
    url(_(r'^bens-de-consumo/$'), ConsumerGoodsListView.as_view(), name="consumer_goods"),
    url(_(r'^alimentos-e-bebidas/$'), FoodBeverageListView.as_view(), name="foods_beverages"),

)

apps/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, include, url
from django.templatetags.i18n import language
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib import admin
from apps.apresentacao.views import *
from apps.contato.views import *
from apps.cotacao.views import *

from django.conf.urls.i18n import i18n_patterns
from django.core.urlresolvers import reverse
from django.utils.translation import activate

from django.utils.translation import ugettext_lazy as _


# urlpatterns = patterns('',
#     # Examples:
#     url(r'^$', TemplateView.as_view(template_name="select-language.html"), name="language"),
# )

urlpatterns = [
    # url(r'^$', LanguageView.as_view()),
    url(r'^$', TemplateView.as_view(template_name="select-language.html"), name="language"),
    url(r'^set_language/(?P<language>[\w-]+)$', LanguageView.as_view(), name="set_language"),
]

urlpatterns += i18n_patterns(
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(_(r'^home/$'), HomeView.as_view(), name="home"),
    url(_(r'^apresentacao/'), include('apps.apresentacao.urls', namespace="apresentacao")),
    url(_(r'^nossos-servicos/'), include('apps.servico.urls', namespace="servico")),
    url(_(r'^produtos/'), include('apps.produto.urls', namespace="produto")),
    url(_(r'^noticias/'), include('apps.noticia.urls', namespace="noticia")),
    url(_(r'^obter-cotacao/'), CotacaoView.as_view(), name="cotacao"),
    url(_(r'^contato/'), ContatoView.as_view(), name="contato"),

    # #url de terceiros
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

apps/produto/models.py
# -*- coding:utf-8 -*-
from apps import settings
from django.db import models
import datetime
import os
from uuid import uuid4
from django.utils.deconstruct import deconstructible
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField
from django.template.defaultfilters import slugify

class Textil(models.Model):

    class Meta:
        verbose_name = 'Textil'
        verbose_name_plural = 'Texteis'

    titulo = models.CharField(u'Titulo', max_length=150)
    texto = RichTextField(u'Texto',blank=True,null=True)
    slug = models.SlugField(u'URL', max_length=150,blank=True,null=True,unique=True)
    idioma = models.CharField(u'Idioma', choices=settings.LANGUAGES, max_length=15)
    date_joined = models.DateTimeField('Criado em',auto_now_add=True)
    date_update = models.DateTimeField('Atualizado em',auto_now=True)

    def __unicode__(self):
        return self.titulo

class Eletronico(models.Model):

    class Meta:
        verbose_name = 'Eletronico'
        verbose_name_plural = 'Eletronicos'

    titulo = models.CharField(u'Titulo', max_length=150)
    texto = RichTextField(u'Texto',blank=True,null=True)
    slug = models.SlugField(u'URL', max_length=150,blank=True,null=True,unique=True)
    idioma = models.CharField(u'Idioma', choices=settings.LANGUAGES, max_length=15)
    date_joined = models.DateTimeField('Criado em',auto_now_add=True)
    date_update = models.DateTimeField('Atualizado em',auto_now=True)

    def __unicode__(self):
        return self.titulo

class Construcao(models.Model):

    class Meta:
        verbose_name = 'Construcao'
        verbose_name_plural = 'Construcoes'

    titulo = models.CharField(u'Titulo', max_length=150)
    texto = RichTextField(u'Texto',blank=True,null=True)
    slug = models.SlugField(u'URL', max_length=150,blank=True,null=True,unique=True)
    idioma = models.CharField(u'Idioma', choices=settings.LANGUAGES, max_length=15)
    date_joined = models.DateTimeField('Criado em',auto_now_add=True)
    date_update = models.DateTimeField('Atualizado em',auto_now=True)

    def __unicode__(self):
        return self.titulo

class Promocional(models.Model):

    class Meta:
        verbose_name = 'Promocional'
        verbose_name_plural = 'Promocionais'

    titulo = models.CharField(u'Titulo', max_length=150)
    texto = RichTextField(u'Texto',blank=True,null=True)
    slug = models.SlugField(u'URL', max_length=150,blank=True,null=True,unique=True)
    idioma = models.CharField(u'Idioma', choices=settings.LANGUAGES, max_length=15)
    date_joined = models.DateTimeField('Criado em',auto_now_add=True)
    date_update = models.DateTimeField('Atualizado em',auto_now=True)

    def __unicode__(self):
        return self.titulo

class ConsumerGoods(models.Model):

    class Meta:
        verbose_name = u'Bens e consumo'
        verbose_name_plural = u'Bens e consumo'

    titulo = models.CharField(u'Titulo', max_length=150)
    texto = RichTextField(u'Texto', blank=True, null=True)
    slug = models.SlugField(u'URL', max_length=150, blank=True, null=True, unique=True)
    idioma = models.CharField(u'Idioma', choices=settings.LANGUAGES, max_length=15)
    date_joined = models.DateTimeField('Criado em', auto_now_add=True)
    date_update = models.DateTimeField('Atualizado em', auto_now=True)

    def __unicode__(self):
        return self.titulo

class FoodBeverage(models.Model):

    class Meta:
        verbose_name = u'Alimento e bebida'
        verbose_name_plural = u'Alimentos e bebidas'

    titulo = models.CharField(u'Titulo', max_length=150)
    texto = RichTextField(u'Texto', blank=True, null=True)
    slug = models.SlugField(u'URL', max_length=150,blank=True,null=True,unique=True)
    idioma = models.CharField(u'Idioma', choices=settings.LANGUAGES, max_length=15)
    date_joined = models.DateTimeField('Criado em',auto_now_add=True)
    date_update = models.DateTimeField('Atualizado em',auto_now=True)

    def __unicode__(self):
        return self.titulo

apps/produto/forms.py
# -*- coding:utf-8 -*-
from django.forms import ModelForm
from django.contrib.auth.models import User
from apps.produto.models import *

apps/produto/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render_to_response, HttpResponse
from apps.produto.models import *
from django.conf import settings
from django.db.models import Q
import datetime
from django.utils.translation import get_language
from django.views.generic import View, TemplateView, ListView, DetailView
from django.utils.html import strip_tags

class TextilListView(ListView):
    
    template_name = 'produto/textil.html'
    model = Textil
    context_object_name = 'texteis'

    def get_queryset(self):

        idioma = get_language()
        texteis = Textil.objects.filter(idioma=idioma)
        queryset = texteis

        return queryset

class EletronicoListView(ListView):

    template_name = 'produto/eletronicos.html'
    model = Eletronico
    context_object_name = 'eletronicos'

    def get_queryset(self):

        idioma = get_language()
        eletronicos = Eletronico.objects.filter(idioma=idioma)
        queryset = eletronicos

        return queryset

class ConstrucaoListView(ListView):

    template_name = 'produto/construcao.html'
    model = Construcao
    context_object_name = 'construcoes'

    def get_queryset(self):

        idioma = get_language()
        construcoes = Construcao.objects.filter(idioma=idioma)
        queryset = construcoes

        return queryset

class PromocionalListView(ListView):

    template_name = 'produto/produtos-promocionais.html'
    model = Promocional
    context_object_name = 'promocionais'

    def get_queryset(self):

        idioma = get_language()
        promocionais = Promocional.objects.filter(idioma=idioma)
        queryset = promocionais

        return queryset

class ConsumerGoodsListView(ListView):

    template_name = 'produto/bens-e-consumo.html'
    model = ConsumerGoods
    context_object_name = 'consumer_goods'

    def get_queryset(self):

        idioma = get_language()
        consumer_goods = ConsumerGoods.objects.filter(idioma=idioma)
        queryset = consumer_goods

        return queryset

class FoodBeverageListView(ListView):

    template_name = 'produto/alimentos-e-bebidas.html'
    model = FoodBeverage
    context_object_name = 'foods_beverages'

    def get_queryset(self):

        idioma = get_language()
        foods_beverages = FoodBeverage.objects.filter(idioma=idioma)
        queryset = foods_beverages

        return queryset

apps/produto/templates/produto/alimentos-e-bebidas.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load i18n %}

{% block  title %}
    {% trans 'Alimentos & Bebidas' %}
{% endblock title %}

{% block content %}
    <section class="home-header interna">
        <div class="bg-title bg-produtos"></div>
        <div class="header-title interna text-center-xs">
            <h1 class="container"><span class="text-light">{% trans 'Produtos' %}</span><br>{% trans 'Alimentos & Bebidas' %}</h1>
        </div>
    </section>
{% endblock content %}

{% block container %}
    <main class=" section-padding content-text">
        {% if foods_beverages %}
            <div class="container">
                {% for food_beverage in foods_beverages %}
                    <div class="row">
                         <div class="col-xs-12">
                            <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{{ food_beverage.titulo }}</h2>
                            <p class="hidding animate" data-animation="transition.slideUpIn">{{ food_beverage.texto|safe|escape }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{% trans 'Em breve mais informações' %}</h2>
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="container action-button hidding animate">
            <div class="col-xs-12"><a href="{% url 'produto:foods_beverages' %}" class="btn btn-small btn-rounded btn-block-mobile">{% trans 'Saiba Mais' %}</a></div>
        </div>
    </main>
{% endblock container %}

apps/produto/templates/produto/bens-e-consumo.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load i18n %}

{% block  title %}
   {% trans 'Bens de consumo' %}
{% endblock title %}

{% block content %}
    <section class="home-header interna">
        <div class="bg-title bg-produtos"></div>
        <div class="header-title interna text-center-xs">
            <h1 class="container"><span class="text-light">{% trans 'Produtos' %}</span><br>{% trans 'Bens de consumo' %}</h1>
        </div>
    </section>
{% endblock content %}

{% block container %}
    <main class=" section-padding content-text">

        {% if promocionais %}
            <div class="container">
                {% for consumer_good in consumer_goods %}
                    <div class="row">
                         <div class="col-xs-12">
                            <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{{ consumer_good.titulo }}</h2>
                            <p class="hidding animate" data-animation="transition.slideUpIn">{{ consumer_good.texto|safe|escape }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{% trans 'Em breve mais informações' %}</h2>
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="container action-button hidding animate">
            <div class="col-xs-12"><a href="{% url 'produto:consumer_goods' %}" class="btn btn-small btn-rounded btn-block-mobile">{% trans 'Saiba Mais' %}</a></div>
        </div>
    </main>
{% endblock container %}

apps/produto/templates/produto/construcao.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load i18n %}

{% block  title %}
   {% trans 'Construção' %}
{% endblock title %}

{% block content %}
    <section class="home-header interna">
        <div class="bg-title bg-produtos"></div>
        <div class="header-title interna text-center-xs">
            <h1 class="container"><span class="text-light">{% trans 'Produtos' %}</span><br>{% trans 'construção' %}</h1>
        </div>
    </section>
{% endblock content %}

{% block container %}
    <main class=" section-padding content-text">
        {% if construcoes %}
            <div class="container">
                {% for construcao in construcoes %}
                    <div class="row">
                        <div class="col-xs-12">
                            <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{{ construcao.titulo }}</h2>
                            <p class="hidding animate" data-animation="transition.slideUpIn">{{ construcao.texto|safe|escape }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{% trans 'Em breve mais informações' %}</h2>
                    </div>
                </div>
            </div>
        {% endif%}

        <div class="container action-button hidding animate">
            <div class="col-xs-12"><a href="{% url 'produto:promocional' %}" class="btn btn-small btn-rounded btn-block-mobile">{% trans 'Saiba Mais' %}</a></div>
        </div>
    </main>
{% endblock container %}

apps/produto/templates/produto/eletronicos.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load i18n %}

{% block  title %}
   {% trans 'Eletrônicos' %}
{% endblock title %}

{% block content %}
    <section class="home-header interna">
        <div class="bg-title bg-produtos"></div>
        <div class="header-title interna text-center-xs">
            <h1 class="container"><span class="text-light">{% trans 'Produtos' %}</span><br>{% trans 'eletrônicos' %}</h1>
        </div>
    </section>
{% endblock content %}

{% block container %}
    <main class=" section-padding content-text">

        {% if eletronicos %}
            <div class="container">
                {% for eletronico in eletronicos %}
                    <div class="row">
                        <div class="col-xs-12">
                            <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{{ eletronico.titulo }}</h2>
                            <p class="hidding animate" data-animation="transition.slideUpIn">{{ eletronico.texto|safe|escape }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{% trans 'Em breve mais informações' %}</h2>
                    </div>
                </div>
            </div>
        {% endif%}

        <div class="container action-button hidding animate">
            <div class="col-xs-12"><a href="{% url 'produto:construcao' %}" class="btn btn-small btn-rounded btn-block-mobile">{% trans 'Saiba Mais' %}</a></div>
        </div>
    </main>
{% endblock container %}

apps/produto/templates/produto/produtos-promocionais.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load i18n %}

{% block  title %}
   {% trans 'Produtos promocionais' %}
{% endblock title %}

{% block content %}
    <section class="home-header interna">
        <div class="bg-title bg-produtos"></div>
        <div class="header-title interna text-center-xs">
            <h1 class="container"><span class="text-light">{% trans 'Produtos' %}</span><br>{% trans 'produtos promocionais' %}</h1>
        </div>
    </section>
{% endblock content %}

{% block container %}
    <main class=" section-padding content-text">

        {% if promocionais %}
            <div class="container">
                {% for promocinal in promocionais %}
                    <div class="row">
                         <div class="col-xs-12">
                            <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{{ promocinal.titulo }}</h2>
                            <p class="hidding animate" data-animation="transition.slideUpIn">{{ promocinal.texto|safe|escape }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{% trans 'Em breve mais informações' %}</h2>
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="container action-button hidding animate">
            <div class="col-xs-12"><a href="{% url 'produto:textil' %}" class="btn btn-small btn-rounded btn-block-mobile">{% trans 'Saiba Mais' %}</a></div>
        </div>
    </main>
{% endblock container %}

apps/produto/templates/produto/textil.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load i18n %}

{% block  title %}
   {% trans 'Têxtil' %}
{% endblock title %}

{% block content %}
    <section class="home-header interna">
        <div class="bg-title bg-produtos"></div>
        <div class="header-title interna text-center-xs">
          <h1 class="container">
              <span class="text-light">
                  {% trans "Produtos" %}
              </span>
              <br>
                {% trans "têxtil" %}
          </h1>
        </div>
    </section>
{% endblock content %}

{% block container %}
    <main class=" section-padding content-text">
        {% if texteis %}
            <div class="container">
                {% for textil in texteis %}
                    <div class="row">
                        <div class="col-xs-12">
                            <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{{ textil.titulo }}</h2>
                            <p class="hidding animate" data-animation="transition.slideUpIn">{{ textil.texto|safe|escape }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{% trans 'Em breve mais informações' %}</h2>
                    </div>
                </div>
            </div>
        {% endif%}

        <div class="container action-button hidding animate">
            <div class="col-xs-12"><a href="{% url 'produto:eletronico' %}" class="btn btn-small btn-rounded btn-block-mobile">{% trans 'Saiba Mais' %}</a></div>
        </div>

    </main>
{% endblock container %}