apps/apresentacao/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, include, url
from apps.apresentacao.views import *
from django.utils.translation import ugettext_lazy as _

urlpatterns = patterns('apps.apresentacao.views',

    url(_(r'^introducao/$'), IntroducaoListView.as_view(), name="introducao"),
    url(_(r'^implantacoes/$'), ImplantacaoListView.as_view(), name="implantacoes"),
    url(_(r'^numeros/$'), NumeroListView.as_view(), name="numeros"),
    url(_(r'^suas-perguntas/$'), PerguntaListView.as_view(), name="suas-perguntas"),

)

apps/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, include, url
from django.templatetags.i18n import language
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib import admin
from apps.apresentacao.views import *
from apps.contato.views import *
from apps.cotacao.views import *

from django.conf.urls.i18n import i18n_patterns
from django.core.urlresolvers import reverse
from django.utils.translation import activate

from django.utils.translation import ugettext_lazy as _


# urlpatterns = patterns('',
#     # Examples:
#     url(r'^$', TemplateView.as_view(template_name="select-language.html"), name="language"),
# )

urlpatterns = [
    # url(r'^$', LanguageView.as_view()),
    url(r'^$', TemplateView.as_view(template_name="select-language.html"), name="language"),
    url(r'^set_language/(?P<language>[\w-]+)$', LanguageView.as_view(), name="set_language"),
]

urlpatterns += i18n_patterns(
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(_(r'^home/$'), HomeView.as_view(), name="home"),
    url(_(r'^apresentacao/'), include('apps.apresentacao.urls', namespace="apresentacao")),
    url(_(r'^nossos-servicos/'), include('apps.servico.urls', namespace="servico")),
    url(_(r'^produtos/'), include('apps.produto.urls', namespace="produto")),
    url(_(r'^noticias/'), include('apps.noticia.urls', namespace="noticia")),
    url(_(r'^obter-cotacao/'), CotacaoView.as_view(), name="cotacao"),
    url(_(r'^contato/'), ContatoView.as_view(), name="contato"),

    # #url de terceiros
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

apps/apresentacao/models.py
# -*- coding:utf-8 -*-
from apps import settings
from django.db import models
import datetime
import os
from uuid import uuid4
from django.utils.deconstruct import deconstructible
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField
from django.template.defaultfilters import slugify

@deconstructible
class PathAndRename(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')
        # set filename as random string
        filename = '%s.%s'%(slugify(ext[0]), ext[-1])
        # return the whole path to the file
        return os.path.join(self.path, filename)

path = "uploads/{:%Y/%m}/".format(datetime.datetime.now())
path_and_rename = PathAndRename(path)

class Introducao(models.Model):

    class Meta:
        verbose_name = 'Introducao'
        verbose_name_plural = 'Introducoes'

    titulo = models.CharField(u'Titulo', max_length=150)
    texto = RichTextField(u'Texto',blank=True,null=True)
    slug = models.SlugField(u'URL', max_length=150,blank=True,null=True,unique=True)
    idioma = models.CharField(u'Idioma', choices=settings.LANGUAGES, max_length=15)
    date_joined = models.DateTimeField('Criado em',auto_now_add=True)
    date_update = models.DateTimeField('Atualizado em',auto_now=True)

    def __unicode__(self):
        return self.titulo

class Implantacao(models.Model):

    class Meta:
        verbose_name = 'Implantacao'
        verbose_name_plural = 'Implantacoes'

    titulo = models.CharField(u'Titulo', max_length=150)
    texto = RichTextField(u'Texto',blank=True,null=True)
    slug = models.SlugField(u'URL', max_length=150,blank=True,null=True,unique=True)
    idioma = models.CharField(u'Idioma', choices=settings.LANGUAGES, max_length=15)
    date_joined = models.DateTimeField('Criado em',auto_now_add=True)
    date_update = models.DateTimeField('Atualizado em',auto_now=True)

    def __unicode__(self):
        return self.titulo

class Numero(models.Model):

    class Meta:
        verbose_name = 'Numero'
        verbose_name_plural = 'Numeros'

    titulo = models.CharField(u'Titulo', max_length=150)
    texto = RichTextField(u'Texto',blank=True,null=True)
    slug = models.SlugField(u'URL', max_length=150,blank=True,null=True,unique=True)
    idioma = models.CharField(u'Idioma', choices=settings.LANGUAGES, max_length=15)
    date_joined = models.DateTimeField('Criado em',auto_now_add=True)
    date_update = models.DateTimeField('Atualizado em',auto_now=True)

    def __unicode__(self):
        return self.titulo

class Pergunta(models.Model):

    class Meta:
        verbose_name = 'Pergunta'
        verbose_name_plural = 'Perguntas'

    titulo = models.CharField(u'Titulo', max_length=150)
    texto = RichTextField(u'Texto',blank=True,null=True)
    slug = models.SlugField(u'URL', max_length=150,blank=True,null=True,unique=True)
    idioma = models.CharField(u'Idioma', choices=settings.LANGUAGES, max_length=15)
    imagem = models.ImageField(u'Imagem', upload_to=path_and_rename, max_length=255,null=True,blank=True,default=None)
    date_joined = models.DateTimeField('Criado em',auto_now_add=True)
    date_update = models.DateTimeField('Atualizado em',auto_now=True)

    def __unicode__(self):
        return self.titulo

apps/apresentacao/forms.py
# -*- coding:utf-8 -*-
from django.forms import ModelForm
from django.contrib.auth.models import User
from apps.apresentacao.models import *

apps/apresentacao/views.py
# -*- coding:utf-8 -*-
from itertools import chain
from django.core.serializers import json
from django.shortcuts import render_to_response, HttpResponse
from apps.apresentacao.models import *
from apps.noticia.models import *
from django.conf import settings
from django.db.models import Q
import datetime
from django.utils import translation
from django.utils.translation import get_language, check_for_language
from django.views.generic import View, TemplateView, ListView, DetailView
from django.utils.html import strip_tags

import json, requests
from pprint import pprint

class HomeView(ListView):

    template_name = 'base.html'
    model = Post
    context_object_name = 'posts'

    now = datetime.datetime.now()

    def get_queryset(self):
        idioma = get_language()
        nf_list = Post.objects.filter(Q(ativo=True) & Q(data_publicacao__lte=self.now) & Q(fixar=True) & Q(idioma=idioma)).order_by('-data_publicacao')[:4]

        n_list = []
        count_n = int(nf_list.count())

        if count_n < 4:
            limit = 4-count_n
            n_list = Post.objects.filter(Q(ativo=True) & Q(data_publicacao__lte=self.now) & Q(fixar=False) & Q(idioma=idioma)).order_by('-data_publicacao')[:limit]


        nitems = list(chain(nf_list, n_list))

        nitems = sorted(nitems, key=lambda instance: instance.data_publicacao,reverse=True)
        nitems = sorted(nitems, key=lambda instance: instance.fixar,reverse=True)

        queryset = nitems
        return queryset

    def render_to_response(self, context, **response_kwargs):
        moedas = {}

        r = requests.get('http://www.apilayer.net/api/live?access_key=c86d3db52bd4dbbd6e6a496dea03f0e8')
        r = json.loads(r._content)

        moedas['USD'] = None
        moedas['EUR'] = None
        moedas['BRL'] = None
        moedas['GBP'] = None
        moedas['INR'] = None
        moedas['CNY'] = None

        if r['quotes']['USDUSD']:
            moedas['USD'] = r['quotes']['USDUSD']
        if r['quotes']['USDEUR']:
            moedas['EUR'] = r['quotes']['USDEUR']
        if r['quotes']['USDBRL']:
            moedas['BRL'] = r['quotes']['USDBRL']
        if r['quotes']['USDGBP']:
            moedas['GBP'] = r['quotes']['USDGBP']
        if r['quotes']['USDINR']:
            moedas['INR'] = r['quotes']['USDINR']
        if r['quotes']['USDCNY']:
            moedas['CNY'] = r['quotes']['USDCNY']


        context['moedas'] = moedas

        response_kwargs.setdefault('content_type', self.content_type)
        return self.response_class(
            request=self.request,
            template=self.get_template_names(),
            context=context,
            **response_kwargs
        )

class LanguageView(ListView):

    template_name = 'select-language.html'

    def post(self, request, *args, **kwargs):

        from django import http

        user_language = request.POST['language']
        translation.activate(user_language)
        response = http.HttpResponseRedirect('home')
        response.set_cookie(settings.LANGUAGE_COOKIE_NAME, user_language)

        return response

    def get(self, request, *args, **kwargs):

        from django import http
        user_language = kwargs['language']
        translation.activate(user_language)
        response = http.HttpResponseRedirect('/home')
        response.set_cookie(settings.LANGUAGE_COOKIE_NAME, user_language)
        return response

class IntroducaoListView(ListView):

    template_name = 'apresentacao/introducao.html'

    model = Introducao

    context_object_name = 'introducoes'

    def get_queryset(self):
        idioma = get_language()
        introducoes = Introducao.objects.filter(idioma=idioma)
        queryset = introducoes
        return queryset

class ImplantacaoListView(ListView):

    template_name = 'apresentacao/implantacoes.html'

    model = Implantacao

    context_object_name = 'implantacoes'

    def get_queryset(self):
        idioma = get_language()

        print idioma

        implantacoes = Implantacao.objects.filter(idioma=idioma)
        queryset = implantacoes
        return queryset

class NumeroListView(ListView):

    template_name = 'apresentacao/numeros.html'

    model = Numero

    context_object_name = 'numeros'

    def get_queryset(self):
        idioma = get_language()
        numeros = Numero.objects.filter(idioma=idioma)
        queryset = numeros
        return queryset

class PerguntaListView(ListView):

    template_name = 'apresentacao/suas-perguntas.html'

    model = Pergunta

    context_object_name = 'perguntas'

    def get_queryset(self):
        idioma = get_language()
        perguntas = Pergunta.objects.filter(idioma=idioma)
        queryset = perguntas
        return queryset

apps/apresentacao/templates/apresentacao/implantacoes.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load i18n %}

{% block  title %}
   {% trans 'Implatações' %}
{% endblock title %}

{% block content %}
    <section class="home-header interna">
        <div class="bg-title bg-implantacoes"></div>
        <div class="header-title interna text-center-xs">
            <h1 class="container"><span class="text-light">{% trans "Apresentação" %}</span><br>{% trans "implantações" %}</h1>
        </div>
    </section>
{% endblock content %}

{% block container %}
    <main class=" section-padding">
        <div class="container content-text">
            {% for implentacao in implantacoes %}
                <div class="row">
                    <div class="col-xs-12">
                        <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{{ implentacao.titulo }}</h2>
                        <p class="hidding animate" data-animation="transition.slideUpIn">{{ implentacao.texto|safe|escape}}</p>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="container action-button hidding animate">
            <div class="col-xs-12"><a href="{% url 'apresentacao:numeros' %}" class="btn btn-small btn-rounded btn-block-mobile">{% trans 'Saiba Mais' %}</a></div>
        </div>
    </main>
{% endblock container %}

apps/apresentacao/templates/apresentacao/introducao.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load i18n %}

{% block  title %}
   {% trans 'Introdução' %}
{% endblock title %}

{% block content %}
    <section class="home-header interna">
        <div class="bg-title bg-introducao"></div>
        <div class="header-title interna text-center-xs">
            <h1 class="container"><span class="text-light">{% trans "Apresentação" %}</span><br>{% trans "introdução" %}</h1>
        </div>
    </section>
{% endblock content %}

{% block container %}
    <main class=" section-padding">
        <div class="container content-text">
            {% for introducao in introducoes %}
                <div class="row">
                    <div class="col-xs-12">
                        <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{{ introducao.titulo }}</h2>
                        <p class="hidding animate" data-animation="transition.slideUpIn">{{ introducao.texto|safe|escape}}</p>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="container action-button hidding animate">
            <div class="col-xs-12"><a href="{% url 'apresentacao:implantacoes' %}" class="btn btn-small btn-rounded btn-block-mobile">{% trans 'Saiba Mais' %}</a></div>
        </div>
    </main>
{% endblock container %}

apps/apresentacao/templates/apresentacao/numeros.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load i18n %}

{% block  title %}
   {% trans 'Números' %}
{% endblock title %}

{% block content %}
    <section class="home-header interna">
        <div class="bg-title bg-numeros"></div>
        <div class="header-title interna text-center-xs">
            <h1 class="container"><span class="text-light">{% trans 'Apresentação' %}</span><br>{% trans 'números' %}</h1>
        </div>
    </section>
{% endblock content %}

{% block container %}
    <main class=" section-padding numeros">

      <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{% trans 'NÚMEROS' %}</h2>
            </div>
        </div>

        <div class="row animate-context content-text" data-stagger="300">
            {% for numero in numeros %}
                <div class="col-xs-12 col-sm-4 hidding">
                    <h1 class="hero">{{ numero.titulo|safe|escape}}</h1>
                    {{ numero.texto|safe|escape }}
                </div>
            {% endfor %}
        </div>

        <div class="container action-button hidding animate">
            <div class="col-xs-12"><a href="{% url 'apresentacao:suas-perguntas' %}" class="btn btn-small btn-rounded btn-block-mobile">{% trans 'Saiba Mais' %}</a></div>
        </div>
      </div>
    </main>
{% endblock container %}

apps/apresentacao/templates/apresentacao/suas-perguntas.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load i18n %}
{% load thumbnail %}

{% block  title %}
   {% trans 'Suas perguntas' %}
{% endblock title %}

{% block content %}
    <section class="home-header interna">
        <div class="bg-title bg-suas-perguntas"></div>
        <div class="header-title interna text-center-xs">
            <h1 class="container">
                <span class="text-light">{% trans 'Apresentação' %}</span>
                <br>{% trans 'SUAS PERGUNTAS' %}
            </h1>
        </div>
    </section>
{% endblock content %}

{% block container %}
    <main class="section-padding">

      <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideUpIn">{% trans 'Suas perguntas' %}</h2>
                <img src="{% static 'img/suas-perguntas/img-1.jpg' %}" class="img-responsive img-hero hidding animate" data-animation="transition.slideDownIn">
            </div>
        </div>

        <div class="row section-margin">

            {% for pergunta in perguntas %}

                <div class="col-sm-3 col-md-2 hidden-xs hidding animate">
                    {% if pergunta.imagem %}
                        {% thumbnail pergunta.imagem "200x115" crop="center" as im %}
                            <img class="img-responsive img-hero" src="{{ im.url }}">
                        {% endthumbnail %}
                    {%else%}
                        {% thumbnail pergunta.imagem_categoria "200x115" crop="center"  as im %}
                            <img class="img-responsive img-hero" src="{{ im.url }}">
                        {% endthumbnail %}
                    {%endif%}
                </div>

                <div class="col-xs-12 col-sm-9 col-md-10 hidding animate">
                    <p class="title-pergunta">{{ pergunta.titulo|safe|escape }}</p>
                    <p class="desc-pergunta">{{pergunta.texto|safe|escape}}</p>
                </div>
            {% endfor %}
        </div>

        <div class="container action-button hidding animate">
            <div class="col-xs-12"><a href="{% url 'apresentacao:introducao' %}" class="btn btn-small btn-rounded btn-block-mobile">{% trans 'Saiba Mais' %}</a></div>
        </div>
      </div>
    </main>
{% endblock container %}