apps/servico/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from apps.servico.views import *
from django.utils.translation import ugettext_lazy as _

urlpatterns = patterns('apps.servico.views',

    url(_(r'^consultoria/$'), ConsultoriaListView.as_view(), name="consultoria"),
    url(_(r'^pesquisa-mercado/$'), PesquisaListView.as_view(), name="pesquisa"),
    url(_(r'^producao/$'), ProducaoListView.as_view(), name="producao"),
    url(_(r'^logistica/$'), LogisticaListView.as_view(), name="logistica"),
)

apps/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, include, url
from django.templatetags.i18n import language
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib import admin
from apps.apresentacao.views import *
from apps.contato.views import *
from apps.cotacao.views import *

from django.conf.urls.i18n import i18n_patterns
from django.core.urlresolvers import reverse
from django.utils.translation import activate

from django.utils.translation import ugettext_lazy as _


# urlpatterns = patterns('',
#     # Examples:
#     url(r'^$', TemplateView.as_view(template_name="select-language.html"), name="language"),
# )

urlpatterns = [
    # url(r'^$', LanguageView.as_view()),
    url(r'^$', TemplateView.as_view(template_name="select-language.html"), name="language"),
    url(r'^set_language/(?P<language>[\w-]+)$', LanguageView.as_view(), name="set_language"),
]

urlpatterns += i18n_patterns(
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(_(r'^home/$'), HomeView.as_view(), name="home"),
    url(_(r'^apresentacao/'), include('apps.apresentacao.urls', namespace="apresentacao")),
    url(_(r'^nossos-servicos/'), include('apps.servico.urls', namespace="servico")),
    url(_(r'^produtos/'), include('apps.produto.urls', namespace="produto")),
    url(_(r'^noticias/'), include('apps.noticia.urls', namespace="noticia")),
    url(_(r'^obter-cotacao/'), CotacaoView.as_view(), name="cotacao"),
    url(_(r'^contato/'), ContatoView.as_view(), name="contato"),

    # #url de terceiros
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

apps/servico/models.py
# -*- coding:utf-8 -*-
from apps import settings
from django.db import models
import datetime
import os
from uuid import uuid4
from django.utils.deconstruct import deconstructible
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField
from django.template.defaultfilters import slugify

class Consultoria(models.Model):

    class Meta:
        verbose_name = 'Consultoria'
        verbose_name_plural = 'Consultorias'

    titulo = models.CharField(u'Titulo', max_length=150)
    texto = RichTextField(u'Texto',blank=True,null=True)
    slug = models.SlugField(u'URL', max_length=150,blank=True,null=True,unique=True)
    idioma = models.CharField(u'Idioma', choices=settings.LANGUAGES, max_length=15)
    date_joined = models.DateTimeField('Criado em',auto_now_add=True)
    date_update = models.DateTimeField('Atualizado em',auto_now=True)

    def __unicode__(self):
        return self.titulo

class Pesquisa(models.Model):

    class Meta:
        verbose_name = 'Pesquisa'
        verbose_name_plural = 'Pesquisas'

    titulo = models.CharField(u'Titulo', max_length=150)
    texto = RichTextField(u'Texto',blank=True,null=True)
    slug = models.SlugField(u'URL', max_length=150,blank=True,null=True,unique=True)
    idioma = models.CharField(u'Idioma', choices=settings.LANGUAGES, max_length=15)
    date_joined = models.DateTimeField('Criado em',auto_now_add=True)
    date_update = models.DateTimeField('Atualizado em',auto_now=True)

    def __unicode__(self):
        return self.titulo

class Producao(models.Model):

    class Meta:
        verbose_name = 'Producao'
        verbose_name_plural = 'Producoes'

    titulo = models.CharField(u'Titulo', max_length=150)
    texto = RichTextField(u'Texto',blank=True,null=True)
    slug = models.SlugField(u'URL', max_length=150,blank=True,null=True,unique=True)
    idioma = models.CharField(u'Idioma', choices=settings.LANGUAGES, max_length=15)
    date_joined = models.DateTimeField('Criado em',auto_now_add=True)
    date_update = models.DateTimeField('Atualizado em',auto_now=True)

    def __unicode__(self):
        return self.titulo

class Logistica(models.Model):

    class Meta:
        verbose_name = 'Logistica'
        verbose_name_plural = 'Logisticas'

    titulo = models.CharField(u'Titulo', max_length=150)
    texto = RichTextField(u'Texto',blank=True,null=True)
    slug = models.SlugField(u'URL', max_length=150,blank=True,null=True,unique=True)
    idioma = models.CharField(u'Idioma', choices=settings.LANGUAGES, max_length=15)
    date_joined = models.DateTimeField('Criado em',auto_now_add=True)
    date_update = models.DateTimeField('Atualizado em',auto_now=True)

    def __unicode__(self):
        return self.titulo

apps/servico/forms.py
# -*- coding:utf-8 -*-
from django.forms import ModelForm
from django.contrib.auth.models import User
from apps.servico.models import *

apps/servico/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render_to_response, HttpResponse
from apps.servico.models import *
from django.conf import settings
from django.db.models import Q
import datetime
from django.utils.translation import get_language
from django.views.generic import View, TemplateView, ListView, DetailView
from django.utils.html import strip_tags

class ConsultoriaListView(ListView):
    
    template_name = 'servico/consultoria.html'

    model = Consultoria

    context_object_name = 'consultorias'

    def get_queryset(self):
        idioma = get_language()
        consultorias = Consultoria.objects.all().filter(idioma=idioma)
        queryset = consultorias
        return queryset

class PesquisaListView(ListView):

    template_name = 'servico/pesquisa-de-mercado.html'

    model = Pesquisa

    context_object_name = 'pesquisas'

    def get_queryset(self):
        idioma = get_language()
        pesquisas = Pesquisa.objects.filter(idioma=idioma)
        queryset = pesquisas
        return queryset

class ProducaoListView(ListView):

    template_name = 'servico/producao.html'

    model = Producao

    context_object_name = 'producoes'

    def get_queryset(self):
        idioma = get_language()
        producoes = Producao.objects.filter(idioma=idioma)
        queryset = producoes
        return queryset

class LogisticaListView(ListView):

    template_name = 'servico/logistica.html'

    model = Logistica

    context_object_name = 'logisticas'

    def get_queryset(self):
        idioma = get_language()
        logisticas = Logistica.objects.filter(idioma=idioma)
        queryset = logisticas
        return queryset

apps/servico/templates/servico/consultoria.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block  title %}
   {% trans 'Consultoria' %}
{% endblock title %}

{% block content %}
    <section class="home-header interna">
        <div class="bg-title bg-consultoria"></div>
        <div class="header-title interna text-center-xs">
            <h1 class="container"><span class="text-light">{% trans 'Nossos Serviços' %}</span><br>{% trans 'consultoria' %}</h1>
        </div>
    </section>
{% endblock content %}

{% block container %}
    <main class="section-padding content-text">
        {% if consultorias %}
            <div class="container">
                {% for consultoria in consultorias %}
                    <div class="row">
                        <div class="col-xs-12">
                            <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideUpIn">{{ consultoria.titulo }}</h2>
                            <p class="hidding animate" data-animation="transition.slideDownIn">{{ consultoria.texto|safe|escape }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{% trans 'Em breve mais informações' %}</h2>
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="container action-button hidding animate">
            <div class="col-xs-12"><a href="{% url 'servico:pesquisa' %}" class="btn btn-small btn-rounded btn-block-mobile">{% trans 'Saiba Mais' %}</a></div>
        </div>

    </main>
{% endblock container %}

apps/servico/templates/servico/logistica.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load i18n %}

{% block  title %}
   {% trans 'Logística' %}
{% endblock title %}

{% block content %}
    <section class="home-header interna">
        <div class="bg-title bg-logistica"></div>
        <div class="header-title interna text-center-xs">
            <h1 class="container"><span class="text-light">{% trans 'Nossos Serviços' %}</span><br>{% trans 'logística' %}</h1>
        </div>
    </section>
{% endblock content %}

{% block container %}
    <main class="section-padding content-text">
        {% if logisticas %}
            <div class="container">
                {% for logistica in logisticas %}
                    <div class="row">
                        <div class="col-xs-12">
                            <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideUpIn">{{ logistica.titulo }}</h2>
                            <p class="hidding animate" data-animation="transition.slideDownIn">{{ logistica.texto|safe|escape }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{% trans 'Em breve mais informações' %}</h2>
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="container action-button hidding animate">
            <div class="col-xs-12"><a href="{% url 'servico:consultoria' %}" class="btn btn-small btn-rounded btn-block-mobile">{% trans 'Saiba Mais' %}</a></div>
        </div>
    </main>
{% endblock container %}

apps/servico/templates/servico/pesquisa-de-mercado.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load i18n %}

{% block  title %}
   {% trans 'Pesquisa de mercado' %}
{% endblock title %}

{% block content %}
    <section class="home-header interna">
        <div class="bg-title bg-pesquisa-mercado"></div>
        <div class="header-title interna text-center-xs">
            <h1 class="container"><span class="text-light">{% trans 'Nossos Serviços' %}</span><br>{% trans 'pesquisa de mercado' %}</h1>
        </div>
    </section>
{% endblock content %}

{% block container %}
    <main class="section-padding content-text">
        {% if pesquisas %}
            <div class="container">
                {% for pesquisa in pesquisas %}
                    <div class="row">
                        <div class="col-xs-12">
                            <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideUpIn">{{ pesquisa.titulo }}</h2>
                            <p class="hidding animate" data-animation="transition.slideDownIn">{{ pesquisa.texto|safe|escape }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{% trans 'Em breve mais informações' %}</h2>
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="container action-button hidding animate">
            <div class="col-xs-12"><a href="{% url 'servico:producao' %}" class="btn btn-small btn-rounded btn-block-mobile">{% trans 'Saiba Mais' %}</a></div>
        </div>
    </main>
{% endblock container %}

apps/servico/templates/servico/producao.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load i18n %}

{% block  title %}
   {% trans 'Produção' %}
{% endblock title %}

{% block content %}
    <section class="home-header interna">
        <div class="bg-title bg-producao"></div>
        <div class="header-title interna text-center-xs">
            <h1 class="container"><span class="text-light">{% trans 'Nossos Serviços' %}</span><br>{% trans 'produção' %}</h1>
        </div>
    </section>
{% endblock content %}

{% block container %}
    <main class="section-padding content-text">

        {% if producoes %}
        <div class="container">
            {% for producao in producoes %}
                <div class="row">
                    <div class="col-xs-12">
                        <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideUpIn">{{ producao.titulo }}</h2>
                        <p class="hidding animate" data-animation="transition.slideDownIn">{{ producao.texto|safe|escape }}</p>
                    </div>
                </div>
            {% endfor%}
        </div>
        {% else %}
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <h2 class="title-bordered-bottom hidding animate" data-animation="transition.slideDownIn">{% trans 'Em breve mais informações' %}</h2>
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="container action-button hidding animate">
            <div class="col-xs-12">
            <a href="{% url 'servico:logistica' %}" class="btn btn-small btn-rounded btn-block-mobile">{% trans 'Saiba Mais' %}</a></div>
        </div>
    </main>
{% endblock container %}